[workspace]
members = ["bevy_dtls", "bevy_renet_dtls"]
resolver = "2"

[workspace.dependencies]
bevy = "0.14.1"
bytes = "1.7.1"
rustls = "0.23.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
