[package]
name = "bevy_renet_dtls"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bytes = { workspace = true }
rustls = { workspace = true }
bevy_dtls = { path = "../bevy_dtls"}
bevy_renet = "0.0.12"
